version: '3.8'

services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: the1tutor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: the1tutor_db
      MYSQL_USER: the1tutor
      MYSQL_PASSWORD: tutorpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - the1tutor-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot 애플리케이션
  app:
    build: .
    container_name: the1tutor-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/the1tutor_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      DB_USERNAME: the1tutor
      DB_PASSWORD: tutorpassword
    ports:
      - "8080:8080"
    networks:
      - the1tutor-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  the1tutor-network:
    driver: bridge 