name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
      
      - name: Get dependencies
        working-directory: ./the1tutor_client
        run: flutter pub get
        
      - name: Enable web
        working-directory: ./the1tutor_client
        run: flutter config --enable-web
        
      - name: Build web
        working-directory: ./the1tutor_client
        run: flutter build web --base-href "/the1tutor_client/"
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./the1tutor_client/build/web 